version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-chat-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - ai-chat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-chat-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ai-chat-network

networks:
  ai-chat-network:
    driver: bridge
