version: '3.8'

services:
  app:
    image: python:3.9-slim
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    # Keep the container running
    command: /bin/sh -c "while sleep 1000; do :; done" 